CREATE TABLE Bid (ProjectID Int NOT NULL, BidID Int NOT NULL, CONSTRAINT PK_BidIDBid PRIMARY KEY (BidID), BidAmount Int NOT NULL, DateMade Date NOT NULL);
CREATE TABLE Employee (PersonID Int NOT NULL, CONSTRAINT PK_PersonIDEmployee PRIMARY KEY (PersonID), DateHired Date NOT NULL, Demographic varchar(10) NOT NULL, Gender varchar(1) NOT NULL, IsUnionMember varchar(1) NOT NULL);
CREATE TABLE EmployeeSkill (PersonID Int NOT NULL, SkillID Int NOT NULL);
CREATE TABLE Equipment (ToolID Int NOT NULL, CONSTRAINT PK_ToolIDEquipment PRIMARY KEY (ToolID), Name varchar(20) NOT NULL, Description Int NOT NULL, IsOwned varchar(1) NOT NULL, CurrentPlace varchar(40) NOT NULL);
CREATE TABLE Inspector (PersonID Int NOT NULL, CONSTRAINT PK_PersonIDInspector PRIMARY KEY (PersonID), OrganizationID Int NOT NULL, qualifications varchar(40) NOT NULL);
CREATE TABLE LineItem (ProjectID Int NOT NULL, LineItemID Int NOT NULL, CONSTRAINT PK_LineItemIDLineItem PRIMARY KEY (LineItemID), MaterialType varchar(10) NOT NULL, Units Int NOT NULL, isOnHand varchar(1) NOT NULL);
CREATE TABLE Location (LocationID Int NOT NULL, CONSTRAINT PK_LocationIDLocation PRIMARY KEY (LocationID), StreetAddress Varchar(40) NOT NULL, City Varchar(40) NOT NULL, State Varchar(40) NOT NULL, ZIP Varchar(40) NOT NULL, SiteVisited Varchar(1) NOT NULL, VisitationNotes Varchar(40) NOT NULL);
CREATE TABLE MaintenanceInstance (ToolID Int NOT NULL, PersonID Int NOT NULL, MaintenanceInstanceID Int NOT NULL, CONSTRAINT PK_MaintenanceInstanceIDMaintenanceInstance PRIMARY KEY (MaintenanceInstanceID), TimeStampStart Date NOT NULL, TimeStampEnd Date NOT NULL, DescriptionOfWork varchar(40) NOT NULL);
CREATE TABLE NotWonProject (ProjectID Int NOT NULL, CONSTRAINT PK_ProjectIDNotWonProject PRIMARY KEY (ProjectID), WinningBidAmount Int NOT NULL);
CREATE TABLE Organization (OrganizationID Int NOT NULL, CONSTRAINT PK_OrganizationIDOrganization PRIMARY KEY (OrganizationID), Name varchar(40) NOT NULL, Email Varchar(40) NOT NULL, StreetAddress Varchar(40) NOT NULL, City Varchar(40) NOT NULL, State Varchar(40) NOT NULL, ZIP Varchar(40) NOT NULL, isState varchar(1) NOT NULL);
CREATE TABLE OwnedEquipment (ToolID Int NOT NULL, CONSTRAINT PK_ToolIDOwnedEquipment PRIMARY KEY (ToolID), Condition varchar(10) NOT NULL);
CREATE TABLE Person (PersonID Int NOT NULL, CONSTRAINT PK_PersonIDPerson PRIMARY KEY (PersonID), LastName Varchar(40) NOT NULL, FirstName Varchar(40) NOT NULL, Email Varchar(40) NOT NULL, StreetAddress Varchar(40) NOT NULL, City Varchar(40) NOT NULL, State Varchar(40) NOT NULL, ZIP Varchar(40) NOT NULL, Type varchar(1) NOT NULL);
CREATE TABLE Quote (OrganizationID Int NOT NULL, LineItemID Int NOT NULL, QuoteID Int NOT NULL, CONSTRAINT PK_QuoteIDQuote PRIMARY KEY (QuoteID), QuotedAmount Int NOT NULL, Status varchar(10) NOT NULL);
CREATE TABLE RentedEquipment (OrganizationID Int NOT NULL, ToolID Int NOT NULL, CONSTRAINT PK_ToolIDRentedEquipment PRIMARY KEY (ToolID), Cost Int NOT NULL, OnHand varchar(1) NOT NULL);
CREATE TABLE Skills (SkillID Int NOT NULL, CONSTRAINT PK_SkillIDSkills PRIMARY KEY (SkillID), StateHourlyRate Int NOT NULL, NonStateHourlyRate Int NOT NULL);
CREATE TABLE WonProject (ProjectID Int NOT NULL, CONSTRAINT PK_ProjectIDWonProject PRIMARY KEY (ProjectID), IsComplete varchar(1) NOT NULL, RecievedPayment varchar(1) NOT NULL);
CREATE TABLE Work (PersonID Int NOT NULL, SkillID Int NOT NULL, ProjectID Int NOT NULL, WorkID Int NOT NULL, CONSTRAINT PK_WorkIDWork PRIMARY KEY (WorkID), TimeStampStart Date NOT NULL, TimeStampEnd Date NOT NULL, IsStateWork varchar(1) NOT NULL);
ALTER TABLE Bid ADD CONSTRAINT FK_ProjectIDBid FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID);
ALTER TABLE Employee ADD CONSTRAINT FK_PersonIDEmployee FOREIGN KEY (PersonID) REFERENCES Person(PersonID);
ALTER TABLE EmployeeSkill ADD CONSTRAINT FK_PersonIDEmployeeSkill FOREIGN KEY (PersonID) REFERENCES Employee(PersonID);
ALTER TABLE EmployeeSkill ADD CONSTRAINT FK_SkillIDEmployeeSkill FOREIGN KEY (SkillID) REFERENCES Skills(SkillID);
ALTER TABLE Inspector ADD CONSTRAINT FK_PersonIDInspector FOREIGN KEY (PersonID) REFERENCES Person(PersonID);
ALTER TABLE Inspector ADD CONSTRAINT FK_OrganizationIDInspector FOREIGN KEY (OrganizationID) REFERENCES Organization(OrganizationID);
ALTER TABLE LineItem ADD CONSTRAINT FK_ProjectIDLineItem FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID);
ALTER TABLE MaintenanceInstance ADD CONSTRAINT FK_ToolIDMaintenanceInstance FOREIGN KEY (ToolID) REFERENCES OwnedEquipment(ToolID);
ALTER TABLE MaintenanceInstance ADD CONSTRAINT FK_PersonIDMaintenanceInstance FOREIGN KEY (PersonID) REFERENCES Employee(PersonID);
ALTER TABLE NotWonProject ADD CONSTRAINT FK_ProjectIDNotWonProject FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID);
ALTER TABLE OwnedEquipment ADD CONSTRAINT FK_ToolIDOwnedEquipment FOREIGN KEY (ToolID) REFERENCES Equipment(ToolID);
ALTER TABLE Project ADD CONSTRAINT FK_OrganizationIDProject FOREIGN KEY (OrganizationID) REFERENCES Organization(OrganizationID);
ALTER TABLE Project ADD CONSTRAINT FK_LocationIDProject FOREIGN KEY (LocationID) REFERENCES Location(LocationID);
ALTER TABLE Quote ADD CONSTRAINT FK_OrganizationIDQuote FOREIGN KEY (OrganizationID) REFERENCES Organization(OrganizationID);
ALTER TABLE Quote ADD CONSTRAINT FK_LineItemIDQuote FOREIGN KEY (LineItemID) REFERENCES LineItem(LineItemID);
ALTER TABLE RentedEquipment ADD CONSTRAINT FK_OrganizationIDRentedEquipment FOREIGN KEY (OrganizationID) REFERENCES Organization(OrganizationID);
ALTER TABLE RentedEquipment ADD CONSTRAINT FK_ToolIDRentedEquipment FOREIGN KEY (ToolID) REFERENCES Equipment(ToolID);
ALTER TABLE WonProject ADD CONSTRAINT FK_ProjectIDWonProject FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID);
ALTER TABLE Work ADD CONSTRAINT FK_PersonIDWork FOREIGN KEY (PersonID) REFERENCES Employee(PersonID);
ALTER TABLE Work ADD CONSTRAINT FK_SkillIDWork FOREIGN KEY (SkillID) REFERENCES Skills(SkillID);
ALTER TABLE Work ADD CONSTRAINT FK_ProjectIDWork FOREIGN KEY (ProjectID) REFERENCES WonProject(ProjectID);
